# Generated by Django 3.2.9 on 2021-12-28 03:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, help_text='Серийный номер', max_length=512, null=True)),
                ('sim', models.CharField(blank=True, help_text='Номер сим-карты', max_length=16, null=True)),
                ('date', models.DateField(help_text='Дата получения')),
                ('dateEnd', models.DateField(blank=True, help_text='Дата сдачи', null=True)),
            ],
            options={
                'ordering': ['devModel', 'sn'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(help_text='Тип', max_length=255)),
            ],
            options={
                'ordering': ['style'],
            },
        ),
        migrations.CreateModel(
            name='MasterRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(help_text='Название компании', max_length=255)),
                ('name', models.CharField(help_text='ФИО мастера проводившего ремонт', max_length=255)),
            ],
            options={
                'ordering': ['comp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Запасная часть', max_length=255)),
                ('desc', models.CharField(help_text='Описание запасной части', max_length=511)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Типа ремонта', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateBegin', models.DateField(blank=True, help_text='Дата начала ремонта', null=True)),
                ('dateEnd', models.DateField(blank=True, help_text='Дата конца ремонта', null=True)),
                ('warranty', models.BooleanField(blank=True, help_text='Гарантия', null=True)),
                ('cause', models.CharField(help_text='Причина', max_length=511)),
                ('diag', models.CharField(help_text='Выявлено при диагностики', max_length=511)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена ремонта', max_digits=9, null=True)),
                ('device', models.ForeignKey(help_text='Устройство', on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
                ('master', models.ForeignKey(blank=True, help_text='Мастер производивший ремонт', null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.masterrepair')),
            ],
            options={
                'ordering': ['-dateBegin', 'device'],
            },
        ),
        migrations.CreateModel(
            name='HistoryRespons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBegin', models.DateTimeField(help_text='Дата получения')),
                ('dateEnd', models.DateTimeField(blank=True, help_text='Дата передачи', null=True)),
                ('device', models.ForeignKey(help_text='Устройство', on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
                ('nextOwner', models.ForeignKey(blank=True, help_text='Следующий ответственный', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoryResponsOwnerNext', to='account.profile')),
                ('owner', models.ForeignKey(help_text='Ответственный', on_delete=django.db.models.deletion.PROTECT, related_name='HistoryResponsOwner', to='account.profile')),
                ('prewOwner', models.ForeignKey(blank=True, help_text='Предыдущий ответственный', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HistoryResponsOwnerPrew', to='account.profile')),
            ],
            options={
                'ordering': ['owner', 'device'],
            },
        ),
        migrations.CreateModel(
            name='DoneRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, help_text='Описание', max_length=511, null=True)),
                ('part', models.ForeignKey(blank=True, help_text='Название запчасти', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.part')),
                ('repair', models.ForeignKey(help_text='Ремонт', on_delete=django.db.models.deletion.PROTECT, to='devices.repair')),
                ('typeRepair', models.ForeignKey(help_text='Тип ремонта', on_delete=django.db.models.deletion.PROTECT, to='devices.typerepair')),
            ],
            options={
                'ordering': ['repair'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(help_text='Производитель', max_length=255)),
                ('model', models.CharField(help_text='Модель', max_length=255)),
                ('style', models.ForeignKey(help_text='Тип устройства', on_delete=django.db.models.deletion.PROTECT, to='devices.devicetype')),
            ],
            options={
                'ordering': ['style', 'mark', 'model'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='devModel',
            field=models.ForeignKey(help_text='Модель устройства', on_delete=django.db.models.deletion.PROTECT, to='devices.devicemodel'),
        ),
    ]
