# Generated by Django 3.2.9 on 2021-12-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.CharField(help_text='Стартовая страница', max_length=255)),
                ('devices', models.BooleanField(help_text='Устройства')),
                ('places', models.BooleanField(help_text='Места и АВШ')),
                ('violations', models.BooleanField(help_text='Нарушения')),
                ('transports', models.BooleanField(help_text='Транспорт')),
                ('ppu', models.BooleanField(help_text='ППУ')),
                ('loadViolations', models.BooleanField(help_text='Загрузка нарушений')),
                ('filePlaces', models.BooleanField(help_text='Файл мест установки')),
                ('group', models.ForeignKey(help_text='Группа', on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
    ]
