# Generated by Django 3.2.9 on 2021-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_access_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access',
            field=models.BooleanField(help_text='Настройка доступа'),
        ),
    ]
